# Generated by Django 5.2.10 on 2026-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='activity_type',
            field=models.CharField(default='General Analysis', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='engagement_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
