# Generated by Django 5.2.10 on 2026-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoanalysis_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='ai_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
