# Generated by Django 5.2.10 on 2026-03-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='key_moments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
