# Generated by Django 5.2.10 on 2026-03-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoanalysis_key_moments'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='activity_ml_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='face_detection_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='human_presence_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='ml_processed',
            field=models.BooleanField(default=False),
        ),
    ]
